<a href="https://colab.research.google.com/github/maskot1977/Python2020/blob/1202/72.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!date

Wed Dec  2 04:50:52 UTC 2020

In [2]:
import urllib.request 

url = "https://github.com/maskot1977/ipython_notebook/blob/master/toydata/Teikoku-Shoin-Japan.xlsx?raw=true"
urllib.request.urlretrieve(url, 'Teikoku-Shoin-Japan.xlsx')

('Teikoku-Shoin-Japan.xlsx', <http.client.HTTPMessage at 0x7fde9d46e6a0>)

In [3]:
import pandas as pd
excel = pd.ExcelFile('Teikoku-Shoin-Japan.xlsx')

In [4]:
for s in enumerate(excel.sheet_names):
    print(s) # シートの名前と番号を列挙

(0, '面積\u3000〔2017年〕')
(1, '人口\u3000〔2018年〕')
(2, '人口密度\u3000〔2018年〕')
(3, '人口増加率\u3000〔2010～2015年〕')
(4, '老年（65歳以上）人口率\u3000〔2018年〕')
(5, '産業別人口割合(2015年)')
(6, '平均寿命（女）\u3000〔2015年〕')
(7, '平均寿命（男）\u3000〔2015年〕')
(8, '耕地面積〔2017年〕')
(9, '耕地率\u3000〔2017年〕')
(10, '森林率・人工林率〔2017年〕')
(11, '小麦の生産\u3000〔2018年〕')
(12, '米の生産\u3000〔2017年〕')
(13, 'さつまいもの生産\u3000〔2017年〕')
(14, 'じゃがいもの生産\u3000〔2017年〕')
(15, '大豆の生産\u3000〔2017年〕')
(16, '落花生の生産\u3000〔2017年〕')
(17, 'キャベツの生産\u3000〔2017年〕')
(18, 'きゅうりの生産\u3000〔2017年〕')
(19, 'すいかの生産\u3000〔2017年〕')
(20, 'だいこんの生産\u3000〔2017年〕')
(21, 'なたねの生産〔2017年〕')
(22, 'にんじんの生産\u3000〔2017年〕')
(23, 'ねぎの生産\u3000〔2017年〕')
(24, 'はくさいの生産\u3000〔2017年〕')
(25, 'ピーマンの生産\u3000〔2017年〕')
(26, 'ほうれん草の生産\u3000〔2017年〕')
(27, '茶（荒茶）の生産\u3000〔2017年〕')
(28, 'いちごの生産\u3000〔2017年〕')
(29, 'うめの生産\u3000〔2017年〕')
(30, 'メロンの生産\u3000〔2017年〕')
(31, '柿の生産\u3000〔2017年〕')
(32, 'さくらんぼの生産\u3000〔2017年〕')
(33, 'みかんの生産\u3000〔2017年〕')
(34, 'ももの生産\u3000〔2017年〕')
(35, 'りんごの生産\u3000〔2017年〕')
(36, '菊の出荷量 〔2017年〕')
(37, 'パンジーの出荷量 〔2017年〕')
(38, '洋ラン類（切り花）の出荷量\u3000〔2017年〕')
(39, 'ブロイラーの飼養羽数\u3000〔2018年〕')
(40, '豚の飼養頭数\u3000〔2018年〕')
(41, '肉牛の飼養頭数\u3000〔2018年〕')
(42, '乳牛の飼養頭数\u3000〔2018年〕')
(43, 'まゆの生産 〔2017年〕')
(44, '農業産出額\u3000〔2017年〕')
(45, '米の産出額\u3000〔2017年〕')
(46, '麦類の産出額\u3000〔2017年〕')
(47, '豆類の産出額\u3000〔2017年〕')
(48, 'いも類の産出額\u3000〔2017年〕')
(49, '野菜の産出額\u3000〔2017年〕')
(50, '果実の産出額\u3000〔2017年〕')
(51, '花きの産出額\u3000〔2017年〕')
(52, '工芸農作物の産出額\u3000〔2017年〕')
(53, '畜産の産出額\u3000〔2017年〕')
(54, '漁業生産量（漁業・養殖業）〔2016年〕')
(55, 'いかの漁獲量\u3000〔2016年〕')
(56, 'かつおの漁獲量\u3000〔2016年〕')
(57, 'さんまの漁獲量\u3000〔2016年〕')
(58, 'まいわしの漁獲量\u3000〔2016年〕')
(59, 'まぐろの漁獲量\u3000〔2016年〕')
(60, 'かきの養殖\u3000〔2016年〕')
(61, 'ほたてがいの養殖\u3000〔2016年〕')
(62, 'わかめの養殖\u3000〔2016年〕')
(63, '素材（原木）の生産\u3000〔2016年〕')
(64, '工業出荷額\u3000〔2016年〕')
(65, '果実酒の生産 〔2016年〕')
(66, '焼ちゅうの生産 〔2016年〕')
(67, '清酒(濁酒を含む)の生産\u3000〔2016年〕')
(68, 'ビールの生産\u3000〔2016年〕')
(69, '石油・石炭製品の生産 〔2016年〕')
(70, '半導体の生産\u3000〔2016年〕')
(71, '産業用ロボットの生産\u3000〔2016年〕')
(72, '自動車（二輪自動車を含む）の生産\u3000〔2016年〕')
(73, '繊維の生産\u3000〔2016年〕')
(74, '鉄鋼の生産\u3000〔2016年〕')
(75, '集積回路の生産\u3000〔2016年〕')
(76, '1人あたりの県民所得\u3000〔2015年〕')
(77, '1人あたりの都市公園面積\u3000〔2017年3月末〕')
(78, '1人あたりの電力需要量\u3000〔2015年〕')
(79, '1日1人あたりのごみ排出量\u3000〔2016年〕')
(80, '下水道の普及率\u3000〔2018年〕')
(81, '1世帯あたりの乗用車台数\u3000〔2018年〕')
(82, '小売業年間販売額\u30002015年')
(83, '公害苦情件数\u3000〔2017年〕')

In [5]:
sheet_index = 2
print(excel.sheet_names[sheet_index])
sheet = excel.parse(excel.sheet_names[sheet_index], header=None) # 2枚目のシートの中身を pandas 形式にする

人口密度　〔2018年〕

In [6]:
sheet

                                            0    1        2
0   出典：平成30年住民基本台帳人口・世帯数表、平成29年全国都道府県市区町村別面積調  NaN      NaN
1                                        県コード   県名  (人/km2）
2                                           1  北海道       64
3                                           2   青森      136
4                                           3   岩手       83
5                                           4   宮城      317
6                                           5   秋田       87
7                                           6   山形      119
8                                           7   福島      139
9                                           8   茨城      484
10                                          9   栃木      310
11                                         10   群馬      313
12                                         11   埼玉     1939
13                                         12   千葉     1221
14                                         13   東京     6216
15                                         14  神奈川     3796
16                                         15   新潟      181
17                                         16   富山      252
18                                         17   石川      275
19                                         18   福井      189
20                                         19   山梨      188
21                                         20   長野      156
22                                         21   岐阜      193
23                                         22   静岡      481
24                                         23   愛知     1460
25                                         24   三重      318
26                                         25   滋賀      353
27                                         26   京都      556
28                                         27   大阪     4649
29                                         28   兵庫      665
30                                         29   奈良      372
31                                         30  和歌山      206
32                                         31   鳥取      163
33                                         32   島根      103
34                                         33   岡山      270
35                                         34   広島      336
36                                         35   山口      228
37                                         36   徳島      183
38                                         37   香川      529
39                                         38   愛媛      246
40                                         39   高知      102
41                                         40   福岡     1029
42                                         41   佐賀      341
43                                         42   長崎      334
44                                         43   熊本      241
45                                         44   大分      184
46                                         45   宮崎      144
47                                         46  鹿児島      180
48                                         47   沖縄      645
49                                         48   全国      338
50                       ＊人口（2018年）/面積（2017年）  NaN      NaN

In [7]:
!date

Wed Dec  2 04:52:02 UTC 2020